In [70]:
-7/3

-2

In [112]:
%precision 10

'%.10f'

In [13]:
y  = 2000
m =1
d = 1

In [14]:
def J(y, m, d):
    return 367*y - (7*(y+(m+9)/12))/4-(3*((y+(m-9)/7)/100 + 1))/4 + 275 * m/9 + d +1721029

In [74]:
def G_JD(Y, M, D):
    return (1461 *(Y + 4800 + (M - 14)/12))/4 +(367 * (M - 2 - 12 * ((M - 14)/12)))/12 - (3 * ((Y + 4900 + (M - 14)/12)/100))/4 + D - 32075

In [79]:
def J_JD(Y, M, D):
    return 367 * Y - (7 * (Y + 5001 + (M - 9)//7))//4 + (275 * M)//9 + D + 1729777

In [86]:
def J1(y, m, d):
    a = np.floor((14-m)/12)
    y = y + 4800 - a
    m = m + 12*a -3
    return d + np.floor((153*m+2)/5)+365*y + np.floor(y/4) - np.floor(y/100) + np.floor(y/400) - 32045

In [80]:
J(2000, 1, 1)

2451543

In [93]:
J1(1900, 1,1)

2415021.0

In [52]:
from  astropy.time import Time

In [102]:
Time(time2).jd

2451545.0

In [108]:
from numpy import cos, sin
def P(T):
    p = np.zeros((3, 3))
    ζ = np.deg2rad((2306.2181 * T + 0.30188 * T**2 + 0.017998 * T**3)/3600)
    z = np.deg2rad((2306.2181 * T + 1.09468 * T**2 + 0.018203 * T**3)/3600)
    θ = np.deg2rad((2004.3109 * T - 0.42665 * T**2- 0.041833 * T**3)/3600)
    p[0, 0] = cos(z) * cos(θ) * cos(ζ) - sin(z) * sin(ζ)
    p[0, 1] = -cos(z) * cos(θ) * sin(ζ) - sin(z) * cos(ζ)
    p[0, 2] = -cos(z) * sin(θ)
    p[1, 0] = sin(z) * cos(θ) * cos(ζ) + cos(z) * sin(ζ)
    p[1, 1] = -sin(z) * cos(θ) * sin(ζ) + cos(z) * cos(ζ)
    p[1, 2] = -sin(z) * sin(θ)
    p[2, 0] = sin(θ) * cos(ζ)
    p[2, 1] = -sin(θ) * sin(ζ)
    p[2, 2] = cos(θ)
    return p

In [110]:
time1 = '1900-01-01T12:00'
time2 = '2000-01-01T12:00'

In [113]:
T = (Time(time1).jd - Time(time2).jd)/36525
P(T)

array([[ 9.9970292724e-01,  2.2352124933e-02,  9.7180131021e-03],
       [-2.2352125114e-02,  9.9975015414e-01, -1.0860658415e-04],
       [-9.7180126848e-03, -1.0864392463e-04,  9.9995277310e-01]])

In [114]:
np.linalg.inv(_)

array([[ 9.9970292724e-01, -2.2352125114e-02, -9.7180126848e-03],
       [ 2.2352124933e-02,  9.9975015414e-01, -1.0864392463e-04],
       [ 9.7180131021e-03, -1.0860658415e-04,  9.9995277310e-01]])

In [119]:
δ0 = np.deg2rad(-(16 + 36/60 + 52/3600))
α0 = np.deg2rad((6+40/60 + 41.3/3600)*15)
p1 = np.array([cos(δ0) * cos(α0), cos(δ0) * sin(α0), sin(δ0)])[:, None]

In [123]:
p0 = np.matmul(np.linalg.inv(P(T)), p1)

In [131]:
np.rad2deg(np.arccos(p0[0]/cos(np.arcsin(p0[-1]))))

array([101.289112044])